### ISSUE TITLE
NULL-deref in an unlikely event of memory allocation failure

### ISSUE THREAD

**Issue by nefigtut** [nhorman/rng-tools#141]
Hello,

This code from `rngd_nistbeacon.c` will cause NULL-deref in an unlikely event of memory allocation failure:

```
static void get_json_byte_array(json_t *parent, char *key, char **val, uint32_t *len)
{
        ...
        newval = malloc(rawlen/2);
        ...
                        newval[j] = tmpval;

```

Unfortunately, I do not see how to fix this easily. In case we just add `if (!newval)` a NULL-deref  will happen later on accessing NULL pointed by `static struct nist_data_block block` `char *` fields.

**Comment by nhorman** [comment]
ew, you're right.

This is the best way I can think to fix it:
https://github.com/nhorman/rng-tools/pull/142

Basically we add return codes to each type parser, and return 0 in the curl parse routine if any one fails.  That will cause curl to abort the whole parsing process and return an error to the caller of curl_easy_perform, which should fix the problem. The xread_nist function will fail, and the next call will attempt to update the nist block again.  Let me know what you think.

**Comment by nefigtut** [comment]
> and the next call will attempt to update the nist block again. 

I do not quite understand the code, honestly. If memory starvation persists, will it make `rngd` to request a NIST block from a server again and again in an endless loop? An endless loop - because if a memory starvation happens, it usually persists and does not resolve by itself in a short time.

**Comment by nhorman** [comment]
well, sort of.  If memory starvation persists, then yes, it will continue to try and fail to get the needed ram.  But that will only continue so long as the memory constraint exists.  Once that is relieved, we break out of the loop.  in the interim, other entropy sources will be tried to gain the needed entropy

**Comment by nefigtut** [comment]
ok, got it. fair enough, i guess.
